const supabase = require('../utils/supabaseClient');
const cohere = require('../utils/cohereClient');
//i tried openai api first but changed it to cohere 
//const openai = require('../utils/openaiClient');
const { sendToSlack } = require('../utils/SendToSlack');






// this code to get  all the  todos
exports.getAllTodos = async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('todos')
      .select('*')
      .order('created_at', { ascending: false });
      
    if (error) throw error;
    
    res.status(200).json(data);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Here im using this to create a new todo
exports.createTodo = async (req, res) => {
  try {
    const { title, description } = req.body;
    
    if (!title) {
      return res.status(400).json({ error: 'Title is required' });
    }
    
    const { data, error } = await supabase
      .from('todos')
      .insert([{ title, description, completed: false }])
      .select();
      
    if (error) throw error;
    
    res.status(201).json(data[0]);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// this part of the code for Deleting  a todo
exports.deleteTodo = async (req, res) => {
  try {
    const { id } = req.params;
    
    const { error } = await supabase
      .from('todos')
      .delete()
      .eq('id', id);
      
    if (error) throw error;
    
    res.status(200).json({ message: 'Todo deleted successfully' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// for Updating the todo
exports.updateTodo = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, description, completed } = req.body;
    
    const { data, error } = await supabase
      .from('todos')
      .update({ title, description, completed })
      .eq('id', id)
      .select();
      
    if (error) throw error;
    
    res.status(200).json(data[0]);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Summarize the given and notcompleted  todos and send them to Slack 
exports.summarizeAndSend = async (req, res) => {
 console.log('Summarize API called');
  try {
    // Get all incomplete todos
    const { data: todos, error } = await supabase
      .from('todos')
      .select('*')
      .eq('completed', false);

    if (error) throw error;

    if (todos.length === 0) {
      return res.status(200).json({
        message: 'No pending todos to summarize',
        slackResult: { success: true, info: 'No todos to send' }
      });
    }


    const todoText = todos.map(todo =>
      `- ${todo.title}${todo.description ? `: ${todo.description}` : ''}`
    ).join('\n');

    // Calling  Cohere.ai to summarize the todos
    const response = await cohere.generate({
      model: 'command-r-plus',
      prompt: `Summarize the following todo list in a helpful and organized way:\n${todoText}`,
      max_tokens: 300,
      temperature: 0.3,
    });

    const summary = response.generations[0].text;

    const slackMessage = `*TODO SUMMARY*\n\n${summary}\n\n_Generated by Todo Summary Assistant_`;

    const slackResult = await sendToSlack(slackMessage);

    res.status(200).json({
      summary,
      slackResult
    });
  } catch (error) {
  console.error('Full error:', error);
  res.status(500).json({ error: error.message || 'Unknown error' });
};
  };